# Generated by Django 5.2.14 on 2026-08-05 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('duration', models.PositiveIntegerField(help_text='مدت زمان به دقیقه', verbose_name='مدت زمان (دقیقه)')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='قیمت پایه (تومان)')),
                ('is_parallel', models.BooleanField(default=False, help_text='آیا این خدمت می\u200cتواند در بین کارهای دیگر و با زمان صفر انجام شود؟', verbose_name='قابلیت انجام موازی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
