# Generated by Django 5.2.14 on 2026-08-06 22:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=120, unique=True, verbose_name='اسلاگ (URL)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0, help_text='عدد کوچک\u200cتر، بالاتر نمایش داده می\u200cشود.', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام خدمت')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=170, unique=True, verbose_name='اسلاگ (URL)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمت')),
                ('duration', models.PositiveIntegerField(default=0, help_text='مدت زمان به دقیقه. برای خدمات موازی (is_parallel) می\u200cتواند صفر باشد.', verbose_name='مدت زمان (دقیقه)')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پایه (تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, help_text='در صورت خالی بودن، تخفیفی اعمال نمی\u200cشود.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت با تخفیف (تومان)')),
                ('is_parallel', models.BooleanField(default=False, help_text='آیا این خدمت می\u200cتواند در بین کارهای دیگر و بدون اشغال ظرفیت زمانی انجام شود؟', verbose_name='قابلیت انجام موازی')),
                ('requires_staff_confirmation', models.BooleanField(default=False, verbose_name='نیاز به تأیید پرسنل')),
                ('requires_deposit', models.BooleanField(default=False, verbose_name='نیاز به بیعانه')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=0, help_text='فقط زمانی که «نیاز به بیعانه» فعال باشد استفاده می\u200cشود.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ بیعانه (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['category__order', 'order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_price__isnull', True), ('discount_price__lt', models.F('base_price')), _connector='OR'), name='service_discount_price_less_than_base_price')],
            },
        ),
    ]
