# Generated by Django 5.2.14 on 2026-08-07 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_display_mode',
            field=models.CharField(choices=[('single', 'قیمت واحد'), ('range', 'محدوده قیمت (از - تا)')], default='single', max_length=10, verbose_name='نحوه\u200cی نمایش قیمت'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='فقط در حالت «محدوده قیمت» استفاده می\u200cشود.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر قیمت نمایشی (تومان)'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='فقط در حالت «محدوده قیمت» استفاده می\u200cشود.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل قیمت نمایشی (تومان)'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_price',
            field=models.BooleanField(default=True, help_text='اگر خاموش باشد، به\u200cجای قیمت، پیامی مثل «برای اطلاع از قیمت تماس بگیرید» نمایش داده می\u200cشود.', verbose_name='نمایش قیمت در سایت'),
        ),
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='قیمت واقعی که مبنای محاسبات سیستم (رزرو/فاکتور) است؛ لزوماً همان چیزی نیست که در سایت نمایش داده می\u200cشود.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پایه (تومان)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='فقط زمانی معنا دارد که «نحوه\u200cی نمایش قیمت» روی «قیمت واحد» باشد.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت با تخفیف (تومان)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='مدت زمان پایه به دقیقه، فقط برای نمایش تخمینی در سایت عمومی. زمان واقعیِ رزرو بعداً از مقدار اختصاصی هر پرسنل (در مدل واسط پرسنل↔خدمت) خوانده می\u200cشود.', verbose_name='مدت زمان پایه (دقیقه)'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price_display_mode', 'single'), models.Q(('price_display_mode', 'range'), ('price_min__isnull', False), ('price_max__isnull', False), ('price_min__lt', models.F('price_max'))), _connector='OR'), name='service_valid_price_range_when_range_mode'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price_display_mode', 'range'), ('discount_price__isnull', False), _negated=True), name='service_no_discount_price_in_range_mode'),
        ),
    ]
