# Generated by Django 5.2.14 on 2026-08-08 12:27

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_alter_category_created_at_alter_category_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=170, unique=True, verbose_name='اسلاگ (URL)')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='عنوان شغلی')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='تصویر پرسنل')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='سابقه\u200cی کار (سال)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('can_manage_own_appointments', models.BooleanField(default=False, help_text='حتی با این مجوز، هر تغییر باید توسط مشتری تأیید شود؛ این فقط اجازه\u200cی ثبتِ درخواستِ تغییر را می\u200cدهد.', verbose_name='مجوز لغو/ویرایش نوبت\u200cهای خود')),
                ('can_toggle_own_availability', models.BooleanField(default=False, help_text='امکان مسدودکردن موقت بازه\u200cهای رزروْنشده\u200cی برنامه\u200cی کاری خودش (بدون نیاز به ثبت مرخصی کامل).', verbose_name='مجوز فعال/غیرفعال\u200cکردن زمان\u200cهای آزاد خود')),
                ('can_upload_portfolio', models.BooleanField(default=False, verbose_name='مجوز آپلود نمونه\u200cکار')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(blank=True, help_text='در صورت خالی بودن، این پرسنل هنوز به پنل ورود ندارد (فقط پروفایل نمایشی است).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='از تاریخ')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='تا تاریخ')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل (اختیاری)')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='staffpanel.staffmember', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'مرخصی',
                'verbose_name_plural': 'مرخصی\u200cها',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staffpanel.staffmember', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'برنامه\u200cی کاری',
                'verbose_name_plural': 'برنامه\u200cهای کاری',
                'ordering': ['staff', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_override', models.PositiveIntegerField(blank=True, help_text='اگر خالی باشد، مدت زمان پایه\u200cی خودِ خدمت استفاده می\u200cشود.', null=True, verbose_name='مدت زمان اختصاصی (دقیقه)')),
                ('price_override', models.DecimalField(blank=True, decimal_places=0, help_text='اگر خالی باشد، قیمت داخلی پایه\u200cی خودِ خدمت استفاده می\u200cشود.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت اختصاصی (تومان)')),
                ('is_active', models.BooleanField(default=True, help_text='غیرفعال یعنی این پرسنل دیگر این خدمت را ارائه نمی\u200cدهد (بدون حذف تاریخچه).', verbose_name='فعال')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_links', to='services.service', verbose_name='خدمت')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='staffpanel.staffmember', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'ارتباط پرسنل و خدمت',
                'verbose_name_plural': 'ارتباط\u200cهای پرسنل و خدمات',
            },
        ),
        migrations.AddField(
            model_name='staffmember',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='staff_members', through='staffpanel.StaffService', to='services.service', verbose_name='خدمات قابل\u200cارائه'),
        ),
        migrations.CreateModel(
            name='StaffTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل (اختیاری)')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to='staffpanel.staffmember', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'بازه\u200cی مسدودشده',
                'verbose_name_plural': 'بازه\u200cهای مسدودشده',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.UniqueConstraint(fields=('staff', 'service'), name='unique_staff_service_pair'),
        ),
    ]
