# Generated by Django 5.2.14 on 2026-08-06 22:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('role_title', models.CharField(help_text='Examples: Hair stylist, Nail artist', max_length=150, verbose_name='Role title')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff/avatars/', verbose_name='Avatar')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10, verbose_name='Gender')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Experience years')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('services', models.ManyToManyField(blank=True, related_name='staff_members', to='services.service', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Staff member',
                'verbose_name_plural': 'Staff members',
                'ordering': ('sort_order', 'first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('week_day', models.PositiveSmallIntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], verbose_name='Week day')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('is_off', models.BooleanField(default=False, verbose_name='Is off')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staffpanel.staffmember', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Staff schedule',
                'verbose_name_plural': 'Staff schedules',
                'ordering': ('staff', 'week_day', 'start_time'),
                'unique_together': {('staff', 'week_day', 'start_time', 'end_time')},
            },
        ),
    ]
