# Generated by Django 5.2.14 on 2026-08-05 00:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('staffpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('appointment_date', models.DateField(verbose_name='Appointment date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No show')], default='pending', max_length=20, verbose_name='Status')),
                ('customer_note', models.TextField(blank=True, verbose_name='Customer note')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin note')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total price')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='staffpanel.staffmember', verbose_name='Staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ('-appointment_date', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=200, verbose_name='Title snapshot')),
                ('duration_snapshot', models.PositiveIntegerField(verbose_name='Duration snapshot')),
                ('price_snapshot', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price snapshot')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.appointment', verbose_name='Appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_items', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Appointment item',
                'verbose_name_plural': 'Appointment items',
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'start_time'], name='booking_app_appoint_b13437_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='booking_app_status_513784_idx'),
        ),
    ]
