# Generated by Django 5.2.14 on 2026-08-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('staffpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='related_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='staffpanel.staffmember', verbose_name='Related staff'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='portfolio.portfoliocategory', verbose_name='Category'),
        ),
    ]
